/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

/**
 * User's dietary goal
 */
export type AnalyzeFoodBodyGoal =
  (typeof AnalyzeFoodBodyGoal)[keyof typeof AnalyzeFoodBodyGoal];

export const AnalyzeFoodBodyGoal = {
  weight_loss: "weight_loss",
  balanced: "balanced",
  weight_gain: "weight_gain",
} as const;
